image: node:20

stages:
  - build

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

admin_frontend_build:
  stage: build
  script:
    - npm ci
    - npm run build
