sql {
    driver = "rlm_sql_postgresql"
    dialect = "postgresql"
    server = "${env:DB_HOST}"
    port = ${env:DB_PORT}
    login = "${env:DB_USER}"
    password = "${env:DB_PASS}"
    radius_db = "${env:DB_NAME}"
    sql_user_name = "%{User-Name}"

    pool {
        start = 5
        min = 4
        max = 10
        spare = 3
        uses = 0
        lifetime = 0
        idle_timeout = 60
    }

    authorize_check_query = "\
        SELECT id, username, attribute, value, op \
        FROM radcheck \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY id"

    authorize_reply_query = "\
        SELECT id, username, attribute, value, op \
        FROM radreply \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY id"

    group_membership_query = "\
        SELECT groupname \
        FROM radusergroup \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY priority"

    authorize_group_check_query = "\
        SELECT id, groupname, attribute, value, op \
        FROM radgroupcheck \
        WHERE groupname = '%{SQL-Group}' \
        ORDER BY id"

    authorize_group_reply_query = "\
        SELECT id, groupname, attribute, value, op \
        FROM radgroupreply \
        WHERE groupname = '%{SQL-Group}' \
        ORDER BY id"

    post_auth_query = "\
        INSERT INTO radpostauth \
            (username, pass, reply, authdate) \
        VALUES \
            ('%{SQL-User-Name}', \
             '%{User-Password:-Chap-Password}', \
             '%{reply:Packet-Type}', \
             NOW())"

    read_groups = no
    deletestaledsessions = yes
    sqltrace = no
    num_sql_socks = 5
    connect_failure_retry_delay = 60
}
